# Generated by Django 4.2.23 on 2025-07-05 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workformentry",
            name="font_size",
            field=models.PositiveSmallIntegerField(
                default=12,
                help_text="생성된 DOCX 내 텍스트 폰트 크기",
                verbose_name="글자 크기(pt)",
            ),
        ),
    ]
