# Generated by Django 5.2.3 on 2025-07-05 15:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_workformentry_font_size"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workformentry",
            name="font_size",
        ),
    ]
