# Generated by Django 5.2.3 on 2025-06-16 10:46

import app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WorkFormDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("folder_name", models.CharField(max_length=255, verbose_name="폴더명")),
                (
                    "docx_file",
                    models.FileField(
                        upload_to=app.models.upload_to, verbose_name="DOCX 파일"
                    ),
                ),
                (
                    "preview_image",
                    models.ImageField(
                        upload_to=app.models.upload_to, verbose_name="미리보기 이미지"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkFormEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("work_date", models.DateField(verbose_name="작업일자")),
                ("location", models.CharField(max_length=100, verbose_name="현장명")),
                ("device", models.CharField(max_length=100, verbose_name="장비명")),
                (
                    "carno",
                    models.CharField(blank=True, max_length=100, verbose_name="차량번호"),
                ),
                ("start_time", models.TimeField(verbose_name="시작시간")),
                ("end_time", models.TimeField(verbose_name="종료시간")),
                ("work_content", models.TextField(verbose_name="작업내용")),
                ("confirm_date", models.DateField(verbose_name="확인일자")),
                (
                    "cert_17",
                    models.CharField(blank=True, max_length=100, verbose_name="차단팀장명"),
                ),
                (
                    "cert_18",
                    models.CharField(blank=True, max_length=100, verbose_name="현장책임자명"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="app.workformdocument",
                    ),
                ),
            ],
        ),
    ]
