# Generated by Django 5.2.3 on 2025-06-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workformentry",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="workformentry",
            name="end_day",
            field=models.CharField(
                choices=[("same", "당일"), ("next", "익일")],
                default="same",
                max_length=10,
                verbose_name="종료일",
            ),
        ),
    ]
