# Generated by Django 5.2.3 on 2025-06-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_workformentry_options_workformentry_end_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="workformdocument",
            name="base_folder",
            field=models.CharField(
                default="", max_length=255, verbose_name="저장 기본 폴더"
            ),
        ),
    ]
