# Generated by Django 5.2.3 on 2025-06-16 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_workformdocument_base_folder"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workformdocument",
            name="base_folder",
        ),
    ]
